# Generated by Django 6.1.1 on 2026-09-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_cities',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='home_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
