# Generated by Django 6.1.1 on 2026-09-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
